Splash
zujkovicstasa/cocktails9 pull request #2
Opened 2024-11-28 14:04 UTC by zujkovicstasa

2024-11-28 17:08 UTC, DunjaMaksimovic9 requested changes
Animation looks great!

2024-11-28 17:08 UTC, dunja-maksimovic-levi9-com commented on cocktails9/cocktails9/ContentView.swift
> +        SplashScreenView()
Feel free to name it just "SplashView"

2024-11-28 17:08 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UILaunchStoryboardName = "Launch Screen.storyboard";
You don't need Launch screen storyboard anymore if you have SwiftUI view as splash

2024-11-28 17:08 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/SplashScreenView.swift
> +    @State private var zoomIn = false
Is zoomIn ever used?

2024-11-28 17:08 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/SplashScreenView.swift
> +                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
It looks like this is obsolete

2024-11-28 17:08 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/SplashScreenView.swift
> +                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)
This too :)

2024-12-02 11:19 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9.xcodeproj/project.pbxproj
> +				INFOPLIST_KEY_UILaunchStoryboardName = "Launch Screen";
You can delete this since you use SplashView for that purpose

2024-12-02 11:19 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/SplashView.swift
> +    @Binding var isActive: Bool
It is this view parent's job to know isActive state, splash should just do its magic when loaded. With that in mind, move isActive var and "onAppear" part to parent view.

2024-12-02 11:19 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/ViewCoordinator.swift
> +struct ViewCoordinator: View {
Since ContentView is by default and by convention starting view, it would be better to keep this logic in it.

2024-12-03 13:17 UTC, nm-levi9 approved these changes

2024-12-03 14:13 UTC, nm-levi9 approved these changes

2024-12-04 14:13 UTC, merged