Main tab
zujkovicstasa/cocktails9 pull request #4
Opened 2024-12-02 10:23 UTC by zujkovicstasa

2024-12-02 14:26 UTC, DunjaMaksimovic9 requested changes

2024-12-02 14:26 UTC, dunja-maksimovic-levi9-com commented on cocktails9/cocktails9/MainTabView.swift
> +                        cocktailsView()
Just capitalize all view names, in code and in file name

2024-12-02 14:26 UTC, dunja-maksimovic-levi9-com commented on cocktails9/cocktails9/MainTabView.swift
> +                Spacer()
It looks like you don't need spacer here

2024-12-03 13:49 UTC, nm-levi9 requested changes

2024-12-03 13:49 UTC, nm-levi9 commented on cocktails9/cocktails9/Views/cocktailsView.swift
> +struct cocktailsView: View {
```suggestion
struct CocktailsView: View {
```

2024-12-03 13:49 UTC, nm-levi9 commented on cocktails9/cocktails9/Views/favoritesView.swift
> +struct favoritesView: View {
```suggestion
struct FavoritesView: View {
```

2024-12-03 13:49 UTC, nm-levi9 commented on cocktails9/cocktails9/Views/profileView.swift
> +struct profileView: View {
```suggestion
struct ProfileView: View {
```

2024-12-03 14:50 UTC, dunja-maksimovic-levi9-com commented
Looks good, just rename file names as well to be capitalized. Tip for renaming things: right click/Refactor/Rename and it does it for you

2024-12-03 14:51 UTC, DunjaMaksimovic9 approved these changes

2024-12-04 14:25 UTC, nm-levi9 approved these changes

2024-12-05 09:21 UTC, merged