Cocktails grid
zujkovicstasa/cocktails9 pull request #6
Opened 2024-12-10 20:39 UTC by zujkovicstasa

2024-12-13 12:52 UTC, DunjaMaksimovic9 requested changes

2024-12-13 12:52 UTC, dunja-maksimovic-levi9-com commented on cocktails9/cocktails9/API/FilterService.swift
> +enum Api {
I would move this enum inside class and use it only for endpoints. Base url is usually separate private let declared inside service class, it makes code more readable.

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/ContentView.swift
>          SplashView(navigateToLogin: $navigateToLogin)
SplashView should know nothing about login or further navigation. It should just be pretty when its parent presents it and be replaced when parent decides. In this case, move presentation logic to ContentView.

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/Helper/FavoriteButton.swift
> +            isFavorite.toggle() // Update the local state of the favorite
This could potentially create a bug if local state is different than reality

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/Model/ResponseList.swift
> +
Consider renaming properties to make it more clear what they are expected to hold

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/ViewModel/CocktailViewModel.swift
> +        if let currentUser = UserManagement.shared.getLoggedInUser() {
Feel free to remove this if let and assign UserManagement.shared.getLoggedInUser() directly to user variable. Both are optionals so end result will be same

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/ViewModel/CocktailViewModel.swift
> +    func applyFilter(filterType: FilterType, value: String) {
You have filter logic in two places :)

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/Views/Cocktails/CocktailItem.swift
> +struct CocktailItem: View {
Just keep naming consistent, 'CocktailItemView'

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/Views/SplashView.swift
> +            Color(Color("splashColor"))
`Color(.splashColor)` or just `Color(.splash)` if you rename it in Assets

2024-12-13 12:52 UTC, dunja-maksimovic-levi9-com commented on cocktails9/cocktails9/Views/Users/RegisterView.swift
> +    let filterService: FilterService
This is not used

2024-12-13 12:52 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/Views/Users/RegisterView.swift
> +    @State private var favoriteCocktails: [Cocktail] = []
This too :)

2024-12-16 13:55 UTC, DunjaMaksimovic9 requested changes

2024-12-16 13:55 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/API/CocktailService.swift
> +    private enum Api {
Use case instead of static let, now it should be error-free

2024-12-16 13:55 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/API/CocktailService.swift
> +        let response: CocktailResponse = try await networkManager.request(from: "\(baseUrl)\(Api.filterAlcoholic)", type: CocktailResponse.self)
```suggestion
        let response: CocktailResponse = try await networkManager.request(from: baseUrl + Api.filterAlcoholic, type: CocktailResponse.self)
```

2024-12-16 13:55 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/API/CocktailService.swift
> +        let url = "\(baseUrl)\(Api.lookup)\(id)"
Similar here `baseUrl + Api.lookup + id`

2024-12-16 13:55 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/API/FilterService.swift
> +    private enum Api {
Here use cases too

2024-12-18 14:42 UTC, nm-levi9 requested changes

2024-12-18 14:42 UTC, n-markovic-levi9-com commented on cocktails9/cocktails9/API/CocktailService.swift
> +        let response: CocktailResponse = try await networkManager.request(from: "\(baseURL)filter.php?a=Alcoholic", type: CocktailResponse.self)
why not use `Api` enum here?

2024-12-18 14:42 UTC, n-markovic-levi9-com commented on cocktails9/cocktails9/API/NetworkManager.swift
> +}
this can be inside `NetworkManger` class

2024-12-18 14:42 UTC, n-markovic-levi9-com commented on cocktails9/cocktails9/ViewModel/CocktailViewModel.swift
> +    func loadFavorites() {
I would rename this to "reloadUser" or something like that, and add a comment that it reloads favorites along with the user data.

2024-12-18 14:42 UTC, n-markovic-levi9-com commented on cocktails9/cocktails9/Views/Cocktails/CocktailsGridView.swift
> +                                    await viewModel.performSearch()
App should not call api immediately on each character typed in. You can use Timer to make this work:

1) define timer in view where the search is `CocktailsGridView` in this case.
```
var inputTimer: Timer?
```

2) cancel previous Timer and  re-schedule it with new action on user input:
```
                            .onChange(of: searchText) { newValue, _ in
                                searchTimer?.invalidate()
                                searchTimer = Timer.scheduledTimer(withTimeInterval: 1, repeats: false, block: { _ in
                                    Task {
                                        // don't store `searchText` in viewModel. You only need it when performing a search
                                        await viewModel.performSearch(query: newValue)
                                    }
                                })
                            }
```
This  should optimize the search functionality, by calling search api only 1 second after user's input

2024-12-18 14:42 UTC, n-markovic-levi9-com commented on cocktails9/cocktails9/Views/Cocktails/CocktailDetailsView.swift
> +                            }
These 3 can be unified into one view and reuse it here.

2024-12-18 14:42 UTC, n-markovic-levi9-com commented on cocktails9/cocktails9/Views/Cocktails/CocktailItem.swift
> +}
Extensions should be in separate files like `View+Extensions.swift`. But more importantly, if you're using this only here, it can be a `private extension`.

2024-12-18 14:42 UTC, n-markovic-levi9-com commented on cocktails9/cocktails9/Views/Cocktails/CocktailsGridView.swift
> +                                .cornerRadius(10)
`.background` modifier is more powerful than you think 🙂 
```suggestion
                                .background(Color.red, in: RoundedRectangle(cornerRadius: 10, style: .circular))
```
so, by using this, you could remove all things from below that is using custom `cornerRadius` func

2024-12-18 14:42 UTC, nm-levi9 commented on cocktails9/cocktails9/Views/Cocktails/CocktailsGridView.swift
> +                            ForEach(viewModel.cocktails.filter { searchText.isEmpty || $0.name.localizedCaseInsensitiveContains(searchText) }, id: \.id) { cocktail in
you don't need to filter searched local data here. Code from above (with `performSearch(:)`) will handle the UI

2024-12-18 14:42 UTC, nm-levi9 commented on cocktails9/cocktails9/Views/Cocktails/CocktailsGridView.swift
> +                            .onChange(of: searchText) { newValue in
```suggestion
                            .onChange(of: searchText) { oldValue, newValue in
```

2024-12-18 14:42 UTC, nm-levi9 commented on cocktails9/cocktails9/Views/Filters/FilterView.swift
> +                    }
This can be a reusable component

2024-12-19 12:13 UTC, DunjaMaksimovic9 requested changes

2024-12-19 12:13 UTC, DunjaMaksimovic9 commented on cocktails9/cocktails9/Model/ResponseList.swift
> +    var alcoholic: String {
Use coding keys for this like in other models

2024-12-19 18:27 UTC, merged